[package]
name = "lp_toolbox"
version = "0.1.0"
edition = "2021"

[features]
default = ["simplex"]
simplex = []

[dependencies]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
